using System;
using System.Collections.Generic;
using System.Text;

namespace JSharp.ByteCode
{
    /// <summary>
    /// Values described here:
    ///     https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.1-200-E.1
    /// </summary>
    [Flags]
    public enum ClassAccessFlags : ushort
    {
        /// <summary>
        /// Declared public; may be accessed from outside its package. 
        /// </summary>
        Public = 0x0001,

        /// <summary>
        /// Declared final; no subclasses allowed. 
        /// </summary>
        Final = 0x0010,

        /// <summary>
        /// Treat superclass methods specially when invoked by the invokespecial instruction. 
        /// </summary>
        Super = 0x0020,

        /// <summary>
        /// Is an interface, not a class.
        /// </summary>
        Interface = 0x0200,

        /// <summary>
        /// Declared abstract; must not be instantiated. 
        /// </summary>
        Abstract = 0x0400,

        /// <summary>
        /// Declared synthetic; not present in the source code. 
        /// </summary>
        Synthetic = 0x1000,

        /// <summary>
        /// Declared as an annotation type.
        /// </summary>
        Annotation = 0x2000,

        /// <summary>
        /// Declared as an enum type. 
        /// </summary>
        Enum = 0x4000
    }

    /// <summary>
    /// Values described here:
    ///     https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.6-200-A.1
    /// </summary>
    [Flags]
    public enum MethodAccessFlags : ushort
    {
        /// <summary>
        /// Declared public; may be accessed from outside its package. 
        /// </summary>
        Public = 0x0001,

        /// <summary>
        /// Declared private; accessible only within the defining class. 
        /// </summary>
        Private = 0x0002,

        /// <summary>
        /// Declared protected; may be accessed within subclasses. 
        /// </summary>
        Protected = 0x0004,

        /// <summary>
        /// Declared static. 
        /// </summary>
        Static = 0x0008,

        /// <summary>
        /// Declared final; must not be overridden (§5.4.5). 
        /// </summary>
        Final = 0x0010,

        /// <summary>
        /// Declared synchronized; invocation is wrapped by a monitor use. 
        /// </summary>
        Synchronized = 0x0020,

        /// <summary>
        /// A bridge method, generated by the compiler.
        /// </summary>
        Bridge = 0x0040,

        /// <summary>
        /// Declared with variable number of arguments.
        /// </summary>
        VarArgs = 0x0080,

        /// <summary>
        /// Declared native; implemented in a language other than Java. 
        /// </summary>
        Native = 0x0100,

        /// <summary>
        /// Declared abstract; no implementation is provided. 
        /// </summary>
        Abstract = 0x0400,

        /// <summary>
        /// Declared strictfp; floating-point mode is FP-strict. 
        /// </summary>
        Strict = 0x0800,

        /// <summary>
        /// Declared synthetic; not present in the source code. 
        /// </summary>
        Synthetic = 0x1000
    }

    /// <summary>
    /// Values described here:
    ///     https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.5-200-A.1
    /// </summary>
    [Flags]
    public enum FieldAccessFlags : ushort
    {
        /// <summary>
        /// Declared public; may be accessed from outside its package. 
        /// </summary>
        Public = 0x0001,

        /// <summary>
        /// Declared private; usable only within the defining class. 
        /// </summary>
        Private = 0x0002,

        /// <summary>
        /// Declared protected; may be accessed within subclasses. 
        /// </summary>
        Protected = 0x0004,

        /// <summary>
        /// Declared static. 
        /// </summary>
        Static = 0x0008,

        /// <summary>
        /// Declared final; never directly assigned to after object construction (JLS §17.5). 
        /// </summary>
        Final = 0x0010,

        /// <summary>
        /// Declared volatile; cannot be cached. 
        /// </summary>
        Volatile = 0x0040,

        /// <summary>
        //// Declared transient; not written or read by a persistent object manager. 
        /// </summary>
        Transient = 0x0080,

        /// <summary>
        /// Declared synthetic; not present in the source code. 
        /// </summary>
        Synthetic = 0x1000,

        /// <summary>
        /// Declared as an element of an enum. 
        /// </summary>
        Enum = 0x4000
    }

    /// <summary>
    /// Values described here:
    ///     https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4-140
    /// </summary>
    public enum ConstantType : byte
    {
        Utf8 = 1,
        Class = 7,
        Fieldref = 9,
        Methodref = 10,
        InterfaceMethodref = 11,
        String = 8,
        Integer = 3,
        Float = 4,
        Long = 5,
        Double = 6,
        NameAndType = 12,
        MethodHandle = 15,
        MethodType = 16,
        InvokeDynamic = 18
    }

    public enum AttributePacketType
    {
        ConstantValue,
        Synthetic,
        Signature,
        Deprecated,
        RuntimeVisibleAnnotations,
        RuntimeInvisibleAnnotations
    }

    [Flags]
    public enum AttributeTarget
    {
        ClassFile = 1,
        Field = 2,
        Method = 4,
        CodeAttribute = 8
    }

    /// <summary>
    /// This values are described here:
    ///     https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-5.html#jvms-5.4.3.5-220
    /// </summary>
    public enum MethodReferenceType : byte
    {
        /// <summary>
        /// Interpretation C.f:T
        /// </summary>
        GetField = 1,

        /// <summary>
        /// Interpretation
        /// </summary>
        GetStatic = 2,

        /// <summary>
        /// Interpretation C.f:T
        /// </summary>
        PutField = 3,

        /// <summary>
        /// Interpretation C.f:T
        /// </summary>
        PutStatic = 4,

        /// <summary>
        /// Interpretation C.m:(A*)T
        /// </summary>
        InvokeVirtual = 5,

        /// <summary>
        /// Interpretation C.m:(A*)T
        /// </summary>
        InvokeStatic = 6,

        /// <summary>
        /// Interpretation C.m:(A*)T
        /// </summary>
        InvokeSpecial = 7,

        /// <summary>
        /// Interpretation C.<init>:(A*)void
        /// </summary>
        NewInvokeSpecial = 8,

        /// <summary>
        /// Interpretation C.m:(A*)T
        /// </summary>
        InvokeInterface = 9
    }

    /// <summary>
    /// Types for ConstantFMIInfo, described here:
    ///     https://docs.oracle.com/javase/specs/jvms/se8/html/jvms-4.html#jvms-4.4.2
    /// </summary>
    public enum ConstantReferenceType
    {
        /// <summary>
        /// Mean that ConstantFMIInfo instance is ConstantFieldrefInfo
        /// </summary>
        FieldReference,

        /// <summary>
        /// Mean that ConstantFMIInfo instance is ConstantMethodrefInfo
        /// </summary>
        MethodReference,

        /// <summary>
        /// Mean that ConstantFMIInfo instance is ConstantInterfaceMethodrefInfo
        /// </summary>
        InterfaceMethodReference
    }
}
